### ISSUE TITLE
Can we compile it without OC servers? OpenJDK 11?

### ISSUE THREAD

**Issue by atranel** [reliatec-gmbh/LibreClinica#172]
Is it possible to compile LibreClinica 1.0 without trying to get modules from OpenClinica servers? I have those modules saved offline so I can recompile OC 3.14, but it would be nice to be able to compile without OC servers. Can we compile LC using OpenJDK 11? OC was working/tested on version 8 only.

**Comment by chae-reliatec** [comment]
Unfortunately it is not possible to compile LibreClinica 1.0 without the OpenClinica servers. We are working hard to make this possible but for the moment at least the lib _org.jmesa:jmesa-oc_ is needed from the OpenClinica repos.
Since we do provide the compiled war archives it shouldn't be an issue for the average user. Users who modify LibreClinica and therefore need to build LibreClinica itself still need the OpenClinica servers.

**Comment by chae-reliatec** [comment]
Unfortunately it is not possible to build LibreClinica 1.0 with OpenJDK 11 and OpenJDK 13. This is the error you will get:

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.3:xjc (schemas-generate) on project LibreClinica-odm: Execution schemas-generate of goal org.codehaus.mojo:jaxb2-maven-plugin:2.3:xjc failed: A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:2.3:xjc: com/sun/codemodel/CodeWriter
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:jaxb2-maven-plugin:2.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
```

**Comment by atranel** [comment]
Thanks for info!

**Comment by toskrip** [comment]
jaxb2-maven-plugin used to generate java classes from xsd scheme have issues with Java 9+. This is relevant for compiling LC not running it. It may be worth investigating if switch to jax-maven-plugin is feasible:

https://github.com/davidmoten/jax-maven-plugin
