### ISSUE TITLE
Issue while connecting to LDAP 

### ISSUE THREAD

**Issue by nancymishra2301** [reliatec-gmbh/LibreClinica#174]
After updating datainfo properties with LDAP connection details when we are trying to add user -> search user in LDAP a popup opens which says "localhost refused to connect.". When we use same properties in OpenClinica it works. 

Is LibreClinica integrated with LDAP for authentication If yes is there a difference in integration steps.

**Comment by chae-reliatec** [comment]
Hi nancymishra2301

LDAP authentication is not part of the tested features yet although there was no change to it and we expected it to work. There shouldn't be a difference in configuration compared to OpenClinica.

Could you provide some output from your logs so that we can dig deeper into this issue.

Regards,
Christian

**Comment by nancymishra2301** [comment]
Hello Christian,

So logs were not giving anything even on "Trace" logging level. 

Then I tried to debug via chrome tools and found below issue:

"Refused to display 'http://localhost:8080/Clinica/pages/listLdapUsers' in a frame because it set 'X-Frame-Options' to 'deny'."

I am using OC 3.15.2 for comparison on same tomcat and browser. 

Anyways I found a workaround :  I can directly call the URL for ldapusers list "http://localhost:8080/Clinica/pages/listLdapUsers" and it comes up. The issue seems limited to frame. 

Nancy

**Comment by chae-reliatec** [comment]
Thank you Nancy for your feedback. 
LibreClinica uses Spring 5 and OpenClinica-3.15 uses Spring 3 that is why the behaviour is different. Spring 5 sets some default values to the response header to improve the security and one of them is the X-Frame-Options.
Thank you for providing a workaround that might be useful to other users.

I'll leave this issue open until a decision is made how and when we will address it.

**Comment by chae-reliatec** [comment]
Some more informations to the spring security headers can be found in the spring documentation.

[14. Security Headers](https://docs.spring.io/spring-security/site/docs/3.2.0.CI-SNAPSHOT/reference/html/headers.html#headers-frame-options)

**Comment by toskrip** [comment]
I reproduced the issue. I see two options. Easiest is to allow the iframe elements given the same origin:

`<security:headers>
        <security:frame-options policy="SAMEORIGIN"/>
</security:headers>`

or we refactor createuseraccount.jsp and listLdapUsers.jsp to not to use iframe. I think this is the only place in code where iframe is used like this to display dialog UI.

**Comment by nancymishra2301** [comment]
Hi Team, 

I have another request regarding LDAP connectivity, the password we are using in configuration is in clear text form. Do we have an option to encrypt it.

Thanks
Nancy

**Comment by toskrip** [comment]
Hi Nancy, 

no plans currently to change this behaviour. It is pretty standard to use clear text configuration values (e.g. it is the same for DB connection string). Encrypting config values does not bring too much of security advantage as the software still need to decrypt those in order to use them and the key for decryption would have to be stored somewhere locally on the machine. For the LDAP connectivity, the account that is specified in config is supposed to be service account (not a personal user account) that grands rights to perform lookups at specified baseDN for user search.

Note: if your LDAP server allows anonymous user lookups, this credentials does not need to be specified (can stay empty).

**Comment by nancymishra2301** [comment]
Thanks Tomas for looking into it. I will look for a workaround to pass security scan. 

Another issue is that when I am trying to connect to LDAP secure port 636 with same configurations application is failing and I am being redirected to error page. While I confirmed that connectivity is fine and I can browse AD via Apache Directory Studio on 636 from same server, application is unable to connect. I am not sure if application was designed to use LDAPS. 

Thanks
Nancy

**Comment by toskrip** [comment]
Regarding LDAPS, this we definitely want to look at. I will create an extra ticket for this so that you can track the progress. As soon as I get a possibility to test LDAP over HTTPS I will start working on it. I believe we will need to create a manual because there will be extra steps needed from LC administrator perspective.

Most LDAP servers will probably use self signed certificate that Java will consider as not trusted. So from administrator perspective, you will need to create a trust store import your LDAP server certificate chain into it and enable the use of it in Java/Tomcat.
