### ISSUE TITLE
LibreClinica Integration with Postgre DB 12

### ISSUE THREAD

**Issue by nancymishra2301** [reliatec-gmbh/LibreClinica#183]
Hi, 

I tired to integrate LibreClinica 1.0 with Postgres DB 12 and got an error related to unsupported OIDs.
Can you please share any details of future plans to integrate LibreClinica with Postgre 12.

Thanks
Nancy

**Comment by atranel** [comment]
That's strange. I run LibreClinica 1.0 with PostgreSQL 12. Maybe some config setting.

**Comment by chae-reliatec** [comment]
Hi Nancy

We tested LibreClinica 1.0 with Postgres 11 since this is the version supported by Debian 10 (Buster). If you have issues with your configuration please try the recommended software versions.

There are currently no specific plans for supporting Postgres 12 since the final release for Postgres 11 is planed for November 9, 2023.

If some experienced community members provide properly tested instructions to install LibreClinica in a different environment  we will happily publish them on libreclinica.org. 
@atranel 
If you think you can provide such an instruction for your configuration please contact me.

Regards,
Christian

**Comment by nancymishra2301** [comment]
Thanks Christian and Atranel for looking into this. 

So I looked at new Postgre release 12.3 yesterday and tried integrating LibreClinica and it WORKED. I will be testing all functionalities in coming days and will let you know if I face any issues. I dont have logs from my previous failed attempts but if I get time will try to reinstall 12.2 and send you error messages. 

Thanks
Nancy
