### ISSUE TITLE
LibreClinica and Participate

### ISSUE THREAD

**Issue by nancymishra2301** [reliatec-gmbh/LibreClinica#194]
Hi Team,

I would like to know if we have any functionality for something corresponding to OpenClinica Participate here. 

We need to collect patient data via mobile/tablet and looking for options to do it via LibreClinica. I started looking into enketo-express-oc for OpenClinica and would like to know if we have similar options here will as well. Also if we have any documentation for integration will be very helpful. 

Thanks
Nancy

**Comment by toskrip** [comment]
Hi Nancy,

I have a bit of experience with ePRO so I will try to answer you question. The rudimentary functionality that would technically allow to use enketo-express-oc together with LibreClinica is present, however it is not something that would be currently possible to use directly out of the box (without changes in code and without setting up extra network security rules in your infrastructure to restrict the OpenRosa interfaces that enketo is using). We have ePRO in a backlog, but as we have community driven development right now there is no volunteer from community that would be willing to contribute such feature to the LibreClinica.

If you need such feature for soon upcoming projects I would probably recommend you to use different ePRO solution and maybe later import data to LibreClinica (if necessary).

best

Tomas

**Comment by nancymishra2301** [comment]
Thank you very much Tom for your prompt response and helping the community with their needs. 

So now to do a Proof of Concept for ePRO I have installed latest community version OpenClinica3.15.7 and enketo-express-oc on local. I don't know if this is right place to ask this but do you have any latest blog or documentation for integrating these 2 applications. I know you had replied to lots of forums back in 2015 but cant find anything latest. 

Thanks
Nancy

**Comment by oba-reliatec** [comment]
Hello Nancy,
as a company supporting the development of LibreClinica (https://libreclinica.org/support.html) we offer an ePRO solution working together with LC, but this is not for free. We are happy to provide you with a quote if you contact us directly (https://www.reliatec.de/en/branchen-loesungen/medizin-it) and let us know your needs.
Kind regards,
Otmar

**Comment by toskrip** [comment]
No problem, I just try to explain what it realistically achievable. You will hit the same limits with OC because you will be still missing one component. The architecture is organised like this:

- an EDC system that serves as form definition backend and where the from data can be also submitted
- enketo which is basically only responsible for web form rendering supporting online/offline data entry
- an extra application (such as Participate, but that one is commercial) that helps to manage the data entry workflows (e.g. allows patient to log in ans see his study progress, which forms are done, which forms are scheduled, jump to data entry on specific form, mark form as completed - not editable anymore)

there are some blockers in the code that will prevent you operate such setup without such an extra application. Technically it is possible to remove those blockers but then you need to deal with security configuration (on network level) to secure enketo to EDC system communication. And all of this is non-validated, probably usable only for non-critical projects. And you need to have people in-house that have experience with customising the code and compiling customised EDC - (that you then need to maintain, merge with new versions when they are released.... I am operating one instance like this  for years so I know how much work it si).

If you just need ePRO to work out of the box, better search for third party solutions (commercial or free). It would be nice if in a future we manage to create the community version of that missing extra application, but right now there is no active development on it.

**Comment by nancymishra2301** [comment]
Thank you Tom for the detailed explanation. This helps a lot. I will keep on searching for alternatives for this like I have started installing odk-central as POC. Will let you know how it goes. 

Thanks
Nancy
