### ISSUE TITLE
LDAP username only allows charcters and underscores

### ISSUE THREAD

**Issue by SethosII** [reliatec-gmbh/LibreClinica#213]
When I try to create new users via LDAP I'm unable to do so because of this error for the field `User Name`:

> The input you provided is not a valid user name in at least 2 alphanumeric or underscore characters format.

I'm unable to edit this field in the account creation form and our LDAP schema doesn't have any attribute that would meet these requirements. Our `displayName` attribute is structured like this: `Surname, Forname` and `sAMAccountName` like this: `forename.surname`.

LibreClinica version 1.0.0

**Comment by toskrip** [comment]
Yes, this behavior is by design. Maybe in a future we could change it and allow also dot character but we need to see what are all the consequences. E.g. I know that ePRO like data submission, for each subject which submits eCRF data on its own, artificial user account is created using OIDs (I think it was study and subject separated by  dot). I could imagine that dot is considered as control character in some application logic (should not be the case but we need to be verify test it before changing rules for valid usernames).

**Comment by chae-reliatec** [comment]
We won't be working on this in the near future.
